//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayukoDem23
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryEmployee
    {
        public int idEmployee { get; set; }
        public Nullable<System.DateTime> DateInput { get; set; }
        public int idInput { get; set; }
        public int idHistory { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual TypeInput TypeInput { get; set; }
    }
}
